### ISSUE TITLE
Support file:// URIs

### ISSUE THREAD

**Issue by ChloeDawn** [packwiz/packwiz-installer#19]
It would be great to see support for local pack metadata in self-contained instances.

`packwiz-installer-bootstrap.jar file://path/to/pack.toml`
`packwiz-installer-bootstrap.jar file://pack.toml`

**Comment by comp500** [comment]
I think this is already supported? You might need an extra slash after `file://`, the syntax is a bit tricky.

**Comment by ChloeDawn** [comment]
`packwiz-installer-bootstrap.jar file://packwiz/pack.toml`

![image](https://user-images.githubusercontent.com/9869940/161449323-7402ba7a-ce22-401e-9621-c48aeed2ca59.png)
`packwiz-installer-bootstrap.jar file:///packwiz/pack.toml`

![image](https://user-images.githubusercontent.com/9869940/161449341-11dbd453-26ec-483e-9d3e-d00494b4b3fd.png)

Executed in a directory containing a subdirectory of `packwiz` which in turn contains `pack.toml`

**Comment by comp500** [comment]
Ah, relative paths aren't supported; you need something like `file:///C:/Users/...`

**Comment by ChloeDawn** [comment]
Ah, thanks! This fixes it:
```batch
setlocal
set pack=%~dp0packwiz/pack.toml
set pack=%pack:\=/%
%~dp0\packwiz-installer-bootstrap.jar "file:///%pack%"
```
