### ISSUE TITLE
 Mods are getting deleted and many errors are encountered

### ISSUE THREAD

**Issue by Hyped1XGeek** [packwiz/packwiz-installer#24]
![Screenshot 2022-05-24 163634](https://user-images.githubusercontent.com/96731982/170021179-707566ae-4ab2-4b87-9e9f-fc9b37a90ad4.png)

Suddenly the autoupdate pack stopped working while launching

I also tried getting the latest modpack from github and it still gives this problem.

By 1/47 in error message it is having problem with all mods

**Comment by comp500** [comment]
Please read the error message, it is telling you to download the mod manually!

> By 1/47 in error message it is having problem with all mods

Not sure what you mean by this, it's only showing 1 mod and stating the error from installing it?

**Comment by Julienraptor01** [comment]
> Please read the error message, it is telling you to download the mod manually!
> 
> > By 1/47 in error message it is having problem with all mods
> 
> Not sure what you mean by this, it's only showing 1 mod and stating the error from installing it?

I helped him on discord so @Hyped1XGeek you can close this.

**Comment by Hyped1XGeek** [comment]
Thanks
