### ISSUE TITLE
Ability to "retry" failed downloads

### ISSUE THREAD

**Issue by IITFA** [packwiz/packwiz-installer#4]
So, it's me again, the noob lol.
After a bit of tinkering, I think I have this thing figured out, but have some suggestions.

One, is the packwiz-installer window is tiny. So tiny that you can't see the full text of what is being downloaded.

Two, the installer seems to have issues when mods fail to download (for example, due to flakey wireless internet). So, when it fails, it just tells the user but doesn't retry. It would probably be better to retry a failed download automatically maybe up to five times before giving up and notifying the user. This "issue" has caused me to have to cancel launch and launch again over twenty times (I lost count) and I still can't complete the launch. It also might be good to reduce the timeout a little mixed with the retries because the timeout is almost agonizing lol.

**Comment by LeoCTH** [comment]
👍 I also have extremely flaky internet and I just can't stand the numerous `Connection timed out: connect`s in my logs after restarting packwiz-installer over and over again. Hope this could be a thing soon

**Comment by TechnoSparks** [comment]
I don't have flaky internet but sometimes the download even fail. I think it's normal when connection is dropping, could be just cursecdn rate limiting the user. 

When the user chose to hit the "cancel launch" button, `packwiz.json` is not written, despite the `jar`s are already download. That means on next bootstraping, packwiz-installer will just download everything again. The player needs to just click on "continue" button, which will generate `packwiz.json`, and [if on MultiMC] will launch the game directly with its instance's modlist not the same with the intended server modlist. At this point, the player have to exit Minecraft and relaunch again, in which packwiz-installer will download any missing files again. If there are still download errors, the aforementioned process have to be repeated.

To mitigate this issue, one way is to distribute your modpacks containing all the JARs too. **This has license ramifications** depending on mods.

A proposed solution is to allow packwiz-installer to generate `packwiz.json` even when not all files are downloaded, in addition to automated retries

**Comment by comp500** [comment]
I'm going to split out the first part of this issue, since it's completely different from the concerns most people are having here.

I've recently (https://github.com/packwiz/packwiz-installer/commit/c6e304bc7f086e16e4852ca6b107320be85c9ea3) added a pass that checks if files on disk are already up to date, so a partially completed modpack download should be resumable now. I still want to add better support for retrying downloads with variable timeouts, so I'll still keep this as an issue.
