### ISSUE TITLE
Handle badly encoded URLs/special characters in paths gracefully (square brackets!)

### ISSUE THREAD

**Issue by comp500** [packwiz/packwiz-installer#5]
See https://github.com/comp500/packwiz-installer/issues/2#issuecomment-813106598 for the current workaround. Ideally I'd like to move to OkHttp, which has a URL class with better handling of unencoded brackets/spaces.

**Comment by NathanYumekoe** [comment]
Is this going to be fixed anytime soon? It appears to be possibly the biggest bug currently around

**Comment by comp500** [comment]
https://github.com/packwiz/packwiz-installer/commit/685e4c71d512f936d4c8c0a10b9010f7b2fb78c7 should fix this once it's integrated with the rest of packwiz-installer, and the targetrewrite branch is released :)
