### ISSUE TITLE
[bug] Index file hash is invalid

### ISSUE THREAD

**Issue by MarioAndWeegee3** [packwiz/packwiz-installer#56]
I'm getting an error when downloading [my modpack](https://github.com/MarioAndWeegee3/create-pack/blob/main/pack.toml).

- I've made sure the git configuration is correct (and have not interacted with the repo on Windows)
- Running `packwiz refresh` does nothing; the hash in the `pack.toml` file is unchanged
- Existing instances are our of date and refuse to update
- Deleting the index file or creating a new instance results in an error message

```
Current version is: null
New version is: v0.5.7
Attempting to update...
Update successful!
Loading manifest file...
Loading pack file...
Loading MultiMC pack file...
MultiMC not detected
Checking local files...
Modpack name: Create Pack
[FATAL] Your index file hash is invalid! The pack developer should packwiz refresh on the pack again
```

**Comment by comp500** [comment]
It seems to work for me... could have just been a caching issue? I'd recommend using Netlify or GitHub Pages, GitHub raw links are not really intended to be used in this way.

**Comment by MarioAndWeegee3** [comment]
Thanks for the help!
