### ISSUE TITLE
Cape Mod has invalid hash?

### ISSUE THREAD

**Issue by t4llfly** [packwiz/packwiz-installer#57]
![image](https://user-images.githubusercontent.com/117188933/225898488-e4512044-01b0-4b5f-b042-d101e998f5cb.png)

**Comment by comp500** [comment]
I think the author re-uploaded the mod with a different file, so the hash is wrong.. try adding it again with `packwiz mr add`?

**Comment by comp500** [comment]
Assuming this is not a packwiz-installer problem
