### ISSUE TITLE
Sided mod support?

### ISSUE THREAD

**Issue by walksanatora** [packwiz/packwiz-installer#59]
I cannot tell any method by which to tell packwiz-installer "only install server mods" or to only install client side mods

**Comment by comp500** [comment]
Use the `--side`/`-s` flag, e.g. `java -jar packwiz-installer-bootstrap.jar -s server [pack url]`

**Comment by walksanatora** [comment]
ah that was not listed as a option in `--help`

**Comment by comp500** [comment]
Yeah the `--help` command is a bit broken at the moment, I'll be fixing it fairly soon.
