### ISSUE TITLE
Packwiz not identifying server properly

### ISSUE THREAD

**Issue by JordanPlayz158** [packwiz/packwiz-installer#62]
I am running packwiz-installer-bootstrap via `java -jar packwiz-installer-bootstrap.jar -g https://path/to/pack.toml` and I have client mods `side = "client"` and both sides mods but yet, I see the server is downloading the client side mods as well, is this expected behavior (if so what is the point of settings the side)? And if not, what determines if the machine is a server or a client? If it is unreliable perhaps there should be a flag added to manually identify the machine as a server or a client? I am running packwiz inside a docker container and am running it through pterodactyl panel (Java 8 image `ghcr.io/pterodactyl/yolks:java_8`).

**Comment by JordanPlayz158** [comment]
> Yeah, I'll transfer it now.
oooo, that is a cool GitHub feature

> Hmmm, could you send the `.pw.toml` of one of the files that doesn't work? Also try deleting `packwiz.json`.

I just did a fresh run and apparently it did not download the client side mods but due to an unrelated network error, it is throwing an error but this could be a bug, packwiz does try to download every mod even if labeled as client side which to me sounds like a bug but maybe it is an intentional design decision?

**Comment by comp500** [comment]
Hmm... are you definitely passing the `-s server` flag? It should be after `java -jar packwiz-installer-bootstrap.jar` since arguments before `-jar` are read by Java and not passed to the launched flag. What's the exact URL you're trying to download from that fails?

**Comment by JordanPlayz158** [comment]
> Hmm... are you definitely passing the -s server flag? It should be after java -jar packwiz-installer-bootstrap.jar since arguments before -jar are read by Java and not passed to the launched flag.

I did pass the `-s server` flag properly, and I am happy and sad to report that it was user error and not a bug (or maybe you may deem it as a bug), I was using a bashism to run `packwiz` then run the server which apparently specifically messed up the last download (it may still be considered the bug because it doesn't flat out fail but strangely fails at the last download
```bash
java -jar packwiz-installer-bootstrap.jar -s server -g https://path/to/pack.toml; java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true $( [[ ! -f unix_args.txt ]] && printf %s "-jar server.jar" || printf %s "@unix_args.txt" )
```

> What's the exact URL you're trying to download from that fails?
https://jordanplayz158.xyz/JordanPlayz158/23smp/-/raw/master/mods/optifine.pw.toml

**Comment by comp500** [comment]
Hmm... the problem seems to be with your server: https://jordanplayz158.xyz/JordanPlayz158/23smp/-/raw/master/nonDistributedMods/OptiFine_1.12.2_HD_U_G5_MOD.jar doesn't download for me in Firefox or curl. The reason it is also downloaded on the server side is because any files you put in a packwiz modpack are included, even if they don't have `.pw.toml` files, so all your `nonDistributedMods` files are downloaded to a folder with the same name - you'll want to add a `.packwizignore` file excluding the `nonDistributedMods` folder.

**Comment by JordanPlayz158** [comment]
Very fascinating, so my assumption that is a network issue was correct, wonder what the cause is because ChickenASM has not reported an error once and it is downloaded from the same source. (And I'm not doing anything fancy to my knowledge, if you are on IPv4, the GitLab instance is proxy passed through nginx but if you are on IPv6 you get a direct line to the GitLab) Also thank you for talking about `.packwizignore` forgot about that and will fix that. But as it sounds like a network error i.e user error on my end, it is my fault and thus, I am sorry for wasting your time without performing (thorough enough) due dilligence and thank you for all the help and guidance
