### ISSUE TITLE
Packwiz doesn't delete removed mods

### ISSUE THREAD

**Issue by ShockedCoder** [packwiz/packwiz-installer#69]
When I delete the metafile for a mod from the mods dir, refresh packwiz, and run packwiz-bootstrap, it still downloads the newly added mods, but doesn't delete the removed mods.

I'm not sure what changed, since this was working just fine a few months ago. I also looked through the wiki to see if there was a change in how non-indexed mods were handled, but I couldn't find anything.

**Comment by comp500** [comment]
Did you delete the `packwiz.json` file? packwiz-installer needs this to remember which files were downloaded as part of the pack and should be removed if they are removed from the pack.

**Comment by ShockedCoder** [comment]
No, I haven't deleted any files.

**Comment by comp500** [comment]
I can't seem to replicate this issue.. could you send your pack, or another pack (before and after removing a file) that causes this behaviour?

**Comment by ShockedCoder** [comment]
I accidentally nuked the device the modpack was on, so I can't help with this anymore.
The next time this happens, I'll open a new issue with more information.

But I've stopped maintaining MC modpacks, so I doubt I'd have any helpful information anytime soon.
