### ISSUE TITLE
Packwiz fails to install mod and its dependency

### ISSUE THREAD

**Issue by Treeway7** [packwiz/packwiz-installer#70]
For some reason, Packwiz Installer does not download [BlossomEnderChest 2.0.2+1.20](https://modrinth.com/mod/blossomenderchest/) and its dependency [BlossomLib](https://modrinth.com/mod/blossomlib), but it does still download other mods (in this case, [ModernFix](https://modrinth.com/mod/modernfix/) and [Mod Menu](https://modrinth.com/mod/modmenu/)).

[Other Blossom series mods](https://modrinth.com/user/CodedSakura) are not affected.

To run this bug reproduction modpack:

1. Download the Auto-Updating instance from the [bug reproduction repository's releases](https://github.com/Treeway7/PackwizModDownloadFails/releases/).
2. Import it in [Prism Launcher](https://prismlauncher.org/).
3. Run the instance.
4. When the loader update prompt appears, click "Continue Anyways".
5. Check the console - it will say BlossomEnderChest and BlossomLib is checked and downloaded..?
6. The mods aren't even in the mods folder... How peculiar! However, ModernFix and Mod Menu did indeed download properly.

Here is the bug reproduction: [Packwiz Mod Download Fails - Bug Reproduction](https://github.com/Treeway7/PackwizModDownloadFails#packwiz-mod-download-fails---bug-reproduction)

**Comment by Treeway7** [comment]
Just found another mod that doesn't download called [Babies Forever](https://modrinth.com/mod/babies-forever).

**Comment by comp500** [comment]
Both of these mods are marked on the Modrinth website as unsupported on the client, so packwiz marks them as server-side mods - these won't be downloaded unless you pass the `--side server` flag to packwiz-installer. You can change this by editing the relevant `.pw.toml` files to use `side = "both"`, which downloads the mods regardless of the `--side` flag.

**Comment by Treeway7** [comment]
Thank you!
