### ISSUE TITLE
Curse forge search broken in many instances

### ISSUE THREAD

**Issue by Yarden-zamir** [packwiz/packwiz-installer#71]
Likely their end but some mods are no findable using packwiz

![Screen Shot 2023-11-02 at 14 32 14](https://github.com/packwiz/packwiz-installer/assets/8178413/5220c06d-acea-4f5e-b66d-cd1e55f7f5bc)

reproduce by running  `packwiz cf add "Jade-Addons"`

**Comment by comp500** [comment]
Entirely a CurseForge problem ([this API call](https://api.curseforge.com/v1/mods/search?classId=6&gameId=432&gameVersion=1.20.1&searchFilter=Jade%20Addons%20(Forge)) doesn't return that mod), not much I can do about it.

**Comment by comp500** [comment]
As a workaround you should be able to use the project URL (`https://www.curseforge.com/minecraft/mc-mods/jade-addons`) or the slug (`jade-addons`).
